name: Debug CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_debug:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

#      - name: Set Up Ruby for fastlane
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: '3.2.3'
#          working-directory: android # will setup files in folder android
#          bundler-cache: true

      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release
#      - run: flutter build apk --debug --split-per-abi

      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Push to Releases GitHub
        uses: ncipollo/release-action@v1
        with:
#          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}


      - name: Upload apk to Firebase distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_TOKEN }}
          # FIREBASE_TOKEN is the json file that i download for notification
          groups: all_testers
          file: build/app/outputs/flutter-apk/app-release.apk
